
modLoader="javafml"

loaderVersion="[40,)"

license="LGPLv3"

[[mods]]

modId="spelunkery"

version = "${version}"

displayName="Spelunkery"

logoFile="icon.png"

credits="Contributors: Bobisnotaperson, ElBones"

authors="Ordana, Keybounce"

itemIcon="spelunkery:rough_diamond"
description='''
An Overhaul to everything Underground
'''

[[dependencies.spelunkery]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.spelunkery]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.spelunkery]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.20-2.12.21,]"
    ordering="NONE"
    side="BOTH"
